---
name: Solutions CI Pipeline

on: pull_request


defaults:
  run:
    working-directory: coding/solutions


jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ktlint
        run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.44.0/ktlint && chmod a+x ktlint
      - name: Linting
        run: ktlint

  tests:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts', '**/gradle.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Run tests
        run: ./gradlew test
